from transformers import pipeline

# ---------------------------
# Choose which model to use
# ---------------------------
# Option 1: Smaller & faster (good for development)
MODEL_NAME = "sshleifer/distilbart-cnn-6-6"  

# Option 2: Larger & better quality (but 1.6GB download)
# MODEL_NAME = "facebook/bart-large-cnn"

print(f"[INFO] Loading summarization model: {MODEL_NAME} ...")

# Load the summarization pipeline
summarizer = pipeline(
    "summarization",
    model=MODEL_NAME
)

def summarize_text(text: str) -> str:
    """
    Summarizes the given text using the selected model.

    Args:
        text (str): Input text to summarize.

    Returns:
        str: Summary text generated by the model.
    """
    if not text or len(text.strip()) == 0:
        print("[WARN] Empty text passed to summarize_text()")
        return ""

    try:
        result = summarizer(
            text,
            max_length=60,   # You can tweak these for better results
            min_length=10,
            do_sample=False
        )
        return result[0].get("summary_text", "")
    except Exception as e:
        print(f"[ERROR] Summarization failed: {e}")
        return "⚠️ Summarization failed. Check logs for details."

